# Site Settings
# Do not use trailing slash (i.e. "/Sample"). For skipping base URL, leave empty quotes ("")
baseurl: " "
url: "https://dr-inamullahkhan.github.io"

# Features Setting
# Turn subpages on or off
publications: True
teaching: True
these: True

# Language of the website
lang: en

# Search engine optimization settings
title: Grape Academic Theme
tagline: A jekyll theme for academic portfolios
description: The demonstration page for the Grape Academic Theme, a jekyll theme for academic portfolios based on the Grape Theme.
author: Christoph Jabs (chrjabs)
twitter:
  username: Inam Ullah
  card: A jekyll theme for academic portfolios
logo: /assets/img/smile.png
social:
  name: Inam Ullah Khan
  links:
    - https://twitter.com/chrjabs
    - https://github.com/chrjabs
locale: en_GB

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true


academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
